examples/ecmascript/es5.ohm
The original ES5 grammar for Ohm is based on OMeta's grammar which in fact is very close to the Appendix A of the ECMAScript 5.1 spec (ECMA-262). This makes it less idiomatic to Ohm and a manual creation of this grammar would look very different, I think.
Here are some refactorings to make the ES5 grammar use more of the Ohm features (not available in grammar notation of the spec).
=> Refactoring ES5 grammar to be more idiomatic

examples/math/index.html, examples/pl0/index.html, examples/viz/index.html
Instead, give unused arguments distinct, descriptive names that start with a leading underscore. This pattern is preferable because it is compatible with strict mode.
Fixes #54.
Note: I checked that the math and viz examples continued to work after this change. The pl0 example was broken before I started; I think it needs maintenance to be brought up to speed with master, but I'm probably the wrong person to do it.
=> Don't duplicate formal arguments

test/test-ohm-syntax.js
And fix duplicate _ arguments.
Fixes #54.
=> Add 'use strict' annotation to test-ohm-syntax

src/pexprs-eval.js
... that makes the variable name `isTopLevelApplication` more accurate in pexprs-eval.js. What do you think, @pdubroy?
=> a little refactoring

test/test-visualizer.js, visualizer/externalRules.js, visualizer/index.js, visualizer/parseTree.js, visualizer/ruleHyperlinks.js, visualizer/searchBar.js
... to create a public `ohmEditor` API and have only one global.
@pdubroy: How do you feel about that?
@lilyx: I know that this changes some things for the semantics editor as well, but my main goal was to refactor the code so I will have an easier way to programmatically load semantics. Please let me know any concerns and I am happy to work this refactoring into the changes on the `sv` branch!
=> Refactoring the visualizer parts

bin/build-debug.sh, bin/watch.sh, package.json
When npm runs on windows (even from git bash) it executes scripts as CMD
scripts. Using `$var` in these scripts causes issues on Windows.
Bash can be invoked however, so moving these scripts into shell files in
the bin directory allows the scripts to be completely bash while still
working on windows.
=> Build on windows successfully

examples/ecmascript/es5.ohm
If there's a rule description on Statement, it masks a number of interesting errors. I saw this when extending the ES5 grammar for my Syndicate/js DSL. I add new cases to Statement expecting input such as `on message foo() { ... }`, and if I forget the `message`, I get an unhelpful error far away from the real problem. Removing the rule description from Statement gets me much more useful error reports.
(Separately, I've fixed a typo: `indentifier` => `identifier`.)
=> Improve es5 errors

src/Grammar.js, src/ohm-cmd.js, src/pexprs-outputRecipe.js
Allow ohm-cmd to generate recipe for ProtoBuiltInRules; useful for bootstrapping. (Second PR; I messed the first one up)
=> Allow ohm-cmd to generate recipe for ProtoBuiltInRules

visualizer/actionButton.js, visualizer/domUtil.js, visualizer/index.js, visualizer/parseTree.js, visualizer/searchBar.js, visualizer/semanticsEditor.js
This moves the definition code for `$` & `$$` into domUtil, and replace `document.querySelector` and `document.querySelectorAll`
=> Visualizer: move `$` and `$$` to domUtil, and replace domcument queries.

src/pexprs-toFailure.js, test/test-pexprs.js
I noticed this when a program written in a grammar parsed by Ohm had a syntax error involving a `Not` wrapping an `Alt`. When the `Not` was turned into a failure, it delegated to its child pexpr, the `Alt`, which has no `toFailure` implementation.
It can be reproduced by supplying input `"b"` to grammar
G { start = ~("b" | "c") "d" }
(The supplied test case does exactly this.)
The commit so far only adds a case for `Alt`; really, the proper fix is probably to add all the other missing cases as well.
Or, it could be that this approach is mistaken - it is, after all, rather verbose! The implementation for `Alt` that I have supplied produces error messages of the form `(x or y or z or ...)`, which isn't great. Could an alternative make sense? What would it be, if so?
=> toFailure is missing cases

visualizer/semanticsEditor.js, visualizer/style/semanticsEditor.css
@lilyx, please take a look.
I found the "+" and "-" characters on the "Force evaluation" menu item a bit confusing. I think it makes more sense to use a standard arrow symbol to indicate that there is a submenu.
=> Viz: Change "Force evaluation" submenu to use triangle rather than +/-

visualizer/exampleWorker.js
In the example generation system, previously, if the example generation worker couldn't generate any examples, the UI would never get a list of needed examples for the worker. Now, on creation, the worker sends its list of needed examples to the UI.
=> Make worker send 'received:neededExamples' on start

README.md
Fir example is missing a `require` statement for ohm-js; generates error as is.  Also added link to the ohm IDE as a great way to get started.
=> adding missing 'require' statement to example in readme, plus link to ohm IDE

src/State.js
Fixes #52 
This PR resolve the issue that the visualizer (and trace) do not always substitute argument with its supplied value. 
In state.eval(expr), expr.eval(state) is called to obtain the result, and then expr is used make the trace entry. The issue occurs because for the Apply expression, substituteParam, which supply the arguments with actual value, is called in expr.eval(state) to make a new Apply expression that is used for the result, while the expr that the state used for tracing is not substituted.
The PR addresses this problem by adding the substitution for Apply in getTraceEntry in State.
=> substitute arguments for apply when making trace entry

doc/syntax-reference.md
Thought it might be nice to mention that these escape forms are supported, since the existing language seems to suggest the ones explicitly listed were the only permissible forms.
=> Mention \x and \u escapes in the syntax reference

examples/operators/.eslintrc.json, examples/operators/README.md, examples/operators/operator-example.js, examples/operators/package.json, examples/operators/test/.eslintrc.json, examples/operators/test/operator-test.js
I wrote an example that walks through, in narrative form, four different ways to specify the grammar and semantics for a language with a nontrivial operator precedence hierarchy.
=> Add the operator example

extras/index.d.ts
Using in TypeScript project:
```
import * as extras from 'ohm-js/extras';
let m = this.grammar.match(source);
if (m.succeeded()) {
let ast = extras.toAST(m);
}
```
=> Add type definition file(d.ts) for extras

README.md
Since this group is private it seems like this line should be removed from the public readme. I'm apparently not the only person who has had this issue:
https://github.com/harc/ohm/issues/225
=> Remove private google groups link

examples/operators/README.md, examples/operators/operator-example.js, examples/operators/package-lock.json, examples/operators/package.json, examples/operators/test/operator-test.js
Use ES module import/export syntax (type: module in package.json), use spreads instead of concat, and clean up some parameter names.
=> Modernize Operators Example

.gitignore, doc/syntax-reference.md
Added documentation to `syntax-reference.md` regarding "comments in Ohm grammars". 
Mainly a copy/paste from pdubroy's Discord post  (https://discord.com/channels/779282197152661525/779286160597319680/793738038433808425).
Also:
- ignore IntelliJ files in Git
=> doc: add 'Comment' section in syntax-reference.md

ohm-js/src/Interval.js, ohm-js/test/test-interval.js
This PR resolves https://github.com/harc/ohm/issues/281.
Notes: the test provided only asserts successful integration with `util.getLineAndColumn()` and the returning object shape -- not meant to be exhaustive as this should be done in `test-util` (currently it is only being tested indirectly by `util.getLineAndColumnMessage()` exhaustive unit tests).
=> feat: add `getLineAndColumn()` method to `Interval`

ohm-js/src/util.js, ohm-js/test/test-interval.js, ohm-js/test/test-util.js
This refactors the resulting object from `getLineAndColumn()` to cast to a message when using `toString()` on it. Other interfaces retain their signature but `getLineAndColumnMessage()` now uses this API and its previous implementation was extracted as a private util.
=> feat: add `toString()` method in `getLineAndColumn()` result object

examples/simple-lisp/simple-lisp.js
This PR introduces a simple lisp implementation.
The code is parsed to an AST, and then evaluated in a specified environment.
As a language this Lisp is probably pretty incomplete, but extending the core functions should be fairly straightforward.
This implementation hopes to sit between easy examples like math and csv, and more complex ones like ecmascript.
One thing that I'm unsure about is the implementation of macros in here, @pdubroy already mentioned that it might make sense to have them as a separate pass before "eval", which seems like a good idea - let me know if this is a blocker for getting this merged, and if not then I'd prefer to leave it as "nice to have".
=> simple lisp example

examples/markdown/README.md, examples/markdown/markdown.js, examples/markdown/package.json, examples/markdown/test.md
This adds an example two pass markdown parser. Tested w/ latest ohm-js release. Added blog link explaining how it works.
=> add markdown example

packages/ohm-js/src/Grammar.js, packages/ohm-js/src/Semantics.js, packages/ohm-js/src/pexprs-outputRecipe.js, packages/ohm-js/test/test-recipes.js
Up to ES2018, \u2028 and \u2029 were not allowed in JS string literals, although they are valid in JSON strings. We were escaping these characters in semantics recipes, but not in the grammar recipes. Fix this by doing the replacement in `Grammar.toRecipe()`.
=> fix #322: Don’t emit literal \u2028 or \u2029 in recipes

doc/api-reference.md, doc/releases/ohm-js-16.0.md, examples/ecmascript/src/es5.js, examples/ecmascript/src/es6.js, examples/math/index.html, examples/nl-datalog-syntax/parser.js, examples/viz/index.html, packages/ohm-js/extras/semantics-toAST.js, packages/ohm-js/index.d.ts, packages/ohm-js/scripts/data/index.d.ts.template, packages/ohm-js/src/Grammar.js, packages/ohm-js/src/Semantics.js, packages/ohm-js/test/test-incremental.js, packages/ohm-js/test/test-ohm-syntax.js, packages/ohm-js/test/test-recipes.js, packages/ohm-js/test/test-semantics.js
- Make `_iter` and `_nonterminal` actions take a variable number of arguments, making them compatible with `Action<T>`
- Simplify the index signature for `ActionDict<T>`
=> fix #324: Make signuture of _iter/_nonterminal compatible with Action<T>

doc/syntax-reference.md
This applies to syntactic rules, not "semantic" rules, and may lead to confusion.
=> Correct usage of "semantic" rule

packages/cli/src/cli.js, packages/cli/src/cli.test.mjs, packages/cli/src/commands/index.js, packages/cli/src/commands/match.js, packages/cli/src/testdata/words-fails.txt, packages/cli/src/testdata/words-succeeds.txt, packages/cli/src/testdata/words.ohm
- Adds a `match` subcommand that matches an input file against a given grammar (.ohm or .ohm-bundle.js).
- Addresses part of #71. Still TODO: implement a way to evaluate an operation / attribute.
=> feat(cli): Add `match` subcommand

packages/ohm-js/src/errors.js
The editor does not display the error message correctly
eg. 
```
Test{
a = alnum
b = a<x> 
}
```
editor need full err message with `interval`, line 34
https://github.com/harc/ohm-editor/blob/bb5f9a15d3d0991818139b0fd6e6b06356883751/src/index.js#L26-L42
but ohm hide it 
https://github.com/harc/ohm/blob/cf1e3abfd61944cfa6784176dcf82910a90953b4/packages/ohm-js/src/errors.js#L129-L140
line 139 should be `expr`
sorry I don't know how to test, please check it
=> fix: Wrong parameters

packages/ohm-js/extras/semantics-toAST.js, packages/ohm-js/src/errors.js, packages/ohm-js/test/extras/test-toAST.js, packages/ohm-js/test/test-recipes.js
The problem described in #363 occurs because the import of `ohm-js` pulls in the ES module, while `ohm-js/extras` is a CommonJS module. (This is the [dual-package hazard](https://nodejs.org/api/packages.html#dual-package-hazard).)
This PR eliminates the import of `ohm-js` from the extras module. It's not really required: it was only used for `instanceof` checks and we can skip those and instead check that the methods we need actually exist.
=> Fix #363 by removing imports of ohm-js from extras (it’s not required)

CHANGELOG.md, packages/ohm-js/index.d.ts, packages/ohm-js/package.json, packages/ohm-js/scripts/data/index.d.ts.template, packages/ohm-js/src/CaseInsensitiveTerminal.js, packages/ohm-js/src/MatchState.js, packages/ohm-js/src/Semantics.js, packages/ohm-js/src/nodes.js, packages/ohm-js/src/pexprs-eval.js
- `grammar` only needs to be on the root node. Removing it from the other nodes saves memory.
- `ctorName` becomes a getter defined in the nodes classes, rather than a per-instance property.
- The `primitiveValue` property of wrappers was already deprecated; this PR removes it entirely. The `_value` property of TerminalNodes is also removed.
- Remove the `toJSON()` method on nodes, which was only used for experimental features in the
Ohm Editor.
=> Remove grammar, _value, toJSON() from nodes

packages/ohm-js/index.d.ts
Currently, Node.isOptional is a function returning a boolean, but the typings show it as a property, not a method. Changing it to a method would help many TypeScript users, and I'm running into issues using this function myself.
=> Fix issues with Node.isOptional() typings

CHANGELOG.md, doc/extras.md, packages/ohm-js/extras/semantics-toAST.js, packages/ohm-js/test/extras/test-toAST.js
BREAKING CHANGE: Change the default behavior `toAST` for the built-in list rules (`ListOf` and friends). Both the syntactic (`ListOf`, ...) and lexical versions (`listOf`, ...) are now represented as arrays, with the separators _discarded_. Previously, the syntactic versions were represented by arrays, but with separators _included_, and the lexical versions were represented as strings (just like other lexical rules).
Fixes #394.
=> feat(toAST): by default, represent built-in list rules by arrays

packages/cli/src/cli.js
From https://github.com/ohmjs/ohm/issues/456
Parse ohm's package.json file to obtain the version. cli.js was parsing the package.json in the current directory to obtain the package version.
It now parses its own package.json file, not the one from the project that is using ohm.
=> Fix package.json location (#456)

doc/patterns-and-pitfalls.md
Line 99: change "right-assiciative" to "right-associative".
=> Fix typo in patterns-and-pitfalls.md

doc/errors.md, doc/publishing-grammars.md
Hello,
Found two typos: one is obvious, the other one needs some attention.
Essentially the recommendation for module exports doesn't seem to match the provided example.
Cheers,
=> Fix some typos in documentation

packages/ohm-js/src/semanticsDeferredInit.js, packages/ohm-js/test/test-semantics.js
Adds support for the builtin `asIteration()` semantic operation to `_iter` nodes.
Before, calling `someIterNode.asIteration()` would throw this error:
```
missingSemanticAction: Missing semantic action for '_iter' in operation 'asIteration'.
NOTE: as of Ohm v16, there is no default action for iteration nodes — see 
https://ohmjs.org/d/dsa for details.
```
Now, `asIteration()` will just return the `_iter` node it was called on.
I often found myself switching between `+`/`*` and `ListOf` while writing grammars. This allows semantics to continue to work as intended without changes.
=> fix(semantics): support `asIteration()` for `_iter` nodes

examples/markdown/markdown.mjs
In `examples/markdown/markdown.mjs`, the Italic rule body doesn't work.
Adding `__Something__`, meaning italic, to the markdown in `examples/markdown/test/data/test.md` will result in the following error
```
error: Uncaught ReferenceError: content is not defined
return ['italic', a.children.map((c) => content()).join('')];
```
Add `c`.
=> fix: Incomplete variable
